name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  Check_scretes:
    name: username and password check
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.EXPO_CLI_USERNAME }}
      - run: echo ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: echo Test
  publish:
    name: Install-and-publish
    needs: [ ci, Check_scretes] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: mayur1704
          expo-password: Mayur7671@
      - run: yarn install
      - run: expo publish
       
  ci:
    name: Daily Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
      - run: yarn install
      - run: expo build:android -t app-bundle 
